# Generated by Django 4.1.1 on 2023-04-20 13:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('properties', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
