# Generated by Django 4.1.1 on 2023-04-20 13:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=6)),
                ('nom', models.CharField(max_length=255)),
                ('part75_plus', models.IntegerField(blank=True, default=None, null=True)),
                ('evo75_plus', models.IntegerField(blank=True, default=None, null=True)),
                ('parretrait', models.IntegerField(blank=True, default=None, null=True)),
                ('evo65seuls', models.IntegerField(blank=True, default=None, null=True)),
                ('mediane', models.IntegerField(blank=True, default=None, null=True)),
                ('mediane75', models.IntegerField(blank=True, default=None, null=True)),
                ('partT5', models.IntegerField(blank=True, default=None, null=True)),
                ('partmaison', models.IntegerField(blank=True, default=None, null=True)),
                ('a60ascenseu', models.IntegerField(blank=True, default=None, null=True)),
                ('popasdense', models.IntegerField(blank=True, default=None, null=True)),
                ('partT5rp', models.IntegerField(blank=True, default=None, null=True)),
                ('diffrevenu', models.IntegerField(blank=True, default=None, null=True)),
                ('cadres55an', models.IntegerField(blank=True, default=None, null=True)),
                ('s15_19seuls', models.IntegerField(blank=True, default=None, null=True)),
                ('s20_24seuls', models.IntegerField(blank=True, default=None, null=True)),
                ('t1529total', models.IntegerField(blank=True, default=None, null=True)),
                ('part1524se', models.IntegerField(blank=True, default=None, null=True)),
                ('atlasnb', models.IntegerField(blank=True, default=None, null=True)),
                ('placetud', models.IntegerField(blank=True, default=None, null=True)),
                ('densitplac', models.IntegerField(blank=True, default=None, null=True)),
                ('evojeunes', models.FloatField(blank=True, default=None, null=True)),
                ('T1T2', models.IntegerField(blank=True, default=None, null=True)),
                ('locataires', models.IntegerField(blank=True, default=None, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ('nom', 'pk'),
            },
        ),
    ]
